title: Jenisys
url: "https://jnisys.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

# Default description in social shares for the jekyll-seo-tag gem
description: Jenisys advisory and consultancy

# Author details for the jekyll-seo-tag gem
author:
  name: Kong Yap
  # email:
  # twitter: # twitter username without the @ symbol

# # Social details for the jekyll-seo-tag gem
# social:
#   name: Urban Template
#   links:
#     - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  projects:
    output: true

paginate: 10
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "project"
    values:
      layout: "project"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
